-- 中国图书馆分类法英文名称更新
UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'General Works'
WHERE CODE = 'A';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Collections. Series. Collected works'
WHERE CODE = 'AC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Encyclopedias'
WHERE CODE = 'AE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Dictionaries and other general reference works'
WHERE CODE = 'AG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Indexes'
WHERE CODE = 'AI';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Museums. Collectors and collecting'
WHERE CODE = 'AM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Newspapers'
WHERE CODE = 'AN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Periodicals'
WHERE CODE = 'AP';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Academies and learned societies'
WHERE CODE = 'AS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Yearbooks. Almanacs. Directories'
WHERE CODE = 'AY';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'History of scholarship and learning. The humanities'
WHERE CODE = 'AZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Philosophy. Psychology. Religion'
WHERE CODE = 'B';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Philosophy (General)'
WHERE CODE = 'B';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Logic'
WHERE CODE = 'BC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Speculative philosophy'
WHERE CODE = 'BD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Psychology'
WHERE CODE = 'BF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Aesthetics'
WHERE CODE = 'BH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Ethics'
WHERE CODE = 'BJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Religions. Mythology. Rationalism'
WHERE CODE = 'BL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Judaism'
WHERE CODE = 'BM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Islam. Bahaism. Theosophy, etc.'
WHERE CODE = 'BP';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Buddhism'
WHERE CODE = 'BQ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Christianity'
WHERE CODE = 'BR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'The Bible'
WHERE CODE = 'BS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Doctrinal Theology'
WHERE CODE = 'BT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Practical Theology'
WHERE CODE = 'BV';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Christian Denominations'
WHERE CODE = 'BX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Auxiliary Sciences of History'
WHERE CODE = 'C';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Auxiliary Sciences of History'
WHERE CODE = 'C';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'History of Civilization'
WHERE CODE = 'CB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Archaeology'
WHERE CODE = 'CC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Diplomatics. Archives. Seals'
WHERE CODE = 'CD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Technical Chronology. Calendar'
WHERE CODE = 'CE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Numismatics'
WHERE CODE = 'CJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Inscriptions. Epigraphy'
WHERE CODE = 'CN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Heraldry'
WHERE CODE = 'CR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Genealogy'
WHERE CODE = 'CS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Biography'
WHERE CODE = 'CT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'World History and History of Europe, Asia, Africa, Australia, New Zealand, etc.'
WHERE CODE = 'D';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'History (General)'
WHERE CODE = 'D';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Great Britain'
WHERE CODE = 'DA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Central Europe'
WHERE CODE = 'DAW';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Austria – Liechtenstein – Hungary – Czechoslovakia'
WHERE CODE = 'DB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'France – Andorra – Monaco'
WHERE CODE = 'DC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Germany'
WHERE CODE = 'DD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Greco-Roman World'
WHERE CODE = 'DE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Greece'
WHERE CODE = 'DF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Italy – Malta'
WHERE CODE = 'DG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Low Countries – Benelux Countries'
WHERE CODE = 'DH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Netherlands (Holland)'
WHERE CODE = 'DJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Eastern Europe (General)'
WHERE CODE = 'DJK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Russia. Soviet Union. Former Soviet Republics – Poland'
WHERE CODE = 'DK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Northern Europe. Scandinavia'
WHERE CODE = 'DL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Spain – Portugal'
WHERE CODE = 'DP';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Switzerland'
WHERE CODE = 'DQ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Balkan Peninsula'
WHERE CODE = 'DR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Asia'
WHERE CODE = 'DS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Africa'
WHERE CODE = 'DT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Oceania (South Seas)'
WHERE CODE = 'DU';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Romanies'
WHERE CODE = 'DX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'History of America'
WHERE CODE = 'E';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Local History of the Americas'
WHERE CODE = 'F';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Geography, Anthropology, Recreation'
WHERE CODE = 'G';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Geography (General). Atlases. Maps'
WHERE CODE = 'G';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Mathematical geography. Cartography'
WHERE CODE = 'GA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Physical geography'
WHERE CODE = 'GB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Oceanography'
WHERE CODE = 'GC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Environmental Sciences'
WHERE CODE = 'GE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Human ecology. Anthropogeography'
WHERE CODE = 'GF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Anthropology'
WHERE CODE = 'GN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Folklore'
WHERE CODE = 'GR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Manners and customs (General)'
WHERE CODE = 'GT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Recreation. Leisure'
WHERE CODE = 'GV';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Social Sciences'
WHERE CODE = 'H';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Social sciences (General)'
WHERE CODE = 'H';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Statistics'
WHERE CODE = 'HA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Economic theory. Demography'
WHERE CODE = 'HB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Economic history and conditions'
WHERE CODE = 'HC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Industries. Land use. Labor'
WHERE CODE = 'HD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Transportation and communications'
WHERE CODE = 'HE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Commerce'
WHERE CODE = 'HF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Finance'
WHERE CODE = 'HG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Public finance'
WHERE CODE = 'HJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Sociology (General)'
WHERE CODE = 'HM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Social history and conditions. Social problems. Social reform'
WHERE CODE = 'HN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'The family. Marriage, Women and Sexuality'
WHERE CODE = 'HQ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Societies: secret, benevolent, etc.'
WHERE CODE = 'HS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Communities. Classes. Races'
WHERE CODE = 'HT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Social pathology. Social and public welfare. Criminology'
WHERE CODE = 'HV';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Socialism. Communism. Anarchism'
WHERE CODE = 'HX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political Science'
WHERE CODE = 'J';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'General legislative and executive papers'
WHERE CODE = 'J';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political science (General)'
WHERE CODE = 'JA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political theory'
WHERE CODE = 'JC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political institutions and public administration'
WHERE CODE = 'JF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political institutions and public administration (North America)'
WHERE CODE = 'JJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political institutions and public administration (United States)'
WHERE CODE = 'JK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political institutions and public administration (Canada, Latin America, etc.)'
WHERE CODE = 'JL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political institutions and public administration (Europe)'
WHERE CODE = 'JN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Political institutions and public administration (Asia, Africa, Australia, Pacific Area, etc.)'
WHERE CODE = 'JQ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Local government. Municipal government'
WHERE CODE = 'JS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Colonies and colonization. Emigration and immigration. International migration'
WHERE CODE = 'JV';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'International law, see JZ and KZ (obsolete)'
WHERE CODE = 'JX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'International relations'
WHERE CODE = 'JZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Law'
WHERE CODE = 'K';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Law in general. Comparative and uniform law. Jurisprudence'
WHERE CODE = 'K';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Religious law in general. Comparative religious law. Jurisprudence'
WHERE CODE = 'KB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Jewish law'
WHERE CODE = 'KBM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Islamic law'
WHERE CODE = 'KBP';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'History of canon law'
WHERE CODE = 'KBR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Canon law of Eastern churches'
WHERE CODE = 'KBS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Canon law of Eastern Rite Churches in Communion with the Holy See of Rome'
WHERE CODE = 'KBT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Law of the Roman Catholic Church. The Holy See'
WHERE CODE = 'KBU';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'KD/KDK - United Kingdom and Ireland'
WHERE CODE = 'SUBCLASSES';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'America. North America'
WHERE CODE = 'KDZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Canada'
WHERE CODE = 'KE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'United States'
WHERE CODE = 'KF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Latin America – Mexico and Central America – West Indies. Caribbean area'
WHERE CODE = 'KG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'South America'
WHERE CODE = 'KH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Europe'
WHERE CODE = 'KJKKZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Asia and Eurasia, Africa, Pacific Area, and Antarctica'
WHERE CODE = 'KLKWX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Law of Australia and New Zealand'
WHERE CODE = 'KUKUQ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Law of nations'
WHERE CODE = 'KZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Education'
WHERE CODE = 'L';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Education (General)'
WHERE CODE = 'L';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'History of education'
WHERE CODE = 'LA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Theory and practice of education'
WHERE CODE = 'LB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Special aspects of education'
WHERE CODE = 'LC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Individual institutions – United States'
WHERE CODE = 'LD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Individual institutions – America (except United States)'
WHERE CODE = 'LE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Individual institutions – Europe'
WHERE CODE = 'LF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Individual institutions – Asia, Africa, Indian Ocean islands, Australia, New Zealand, Pacific islands'
WHERE CODE = 'LG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'College and school magazines and papers'
WHERE CODE = 'LH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Student fraternities and societies, United States'
WHERE CODE = 'LJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Textbooks'
WHERE CODE = 'LT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Music'
WHERE CODE = 'M';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Music'
WHERE CODE = 'M';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Literature on music'
WHERE CODE = 'ML';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Instruction and study'
WHERE CODE = 'MT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Fine Arts'
WHERE CODE = 'N';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Visual arts'
WHERE CODE = 'N';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Architecture'
WHERE CODE = 'NA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Sculpture'
WHERE CODE = 'NB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Drawing. Design. Illustration'
WHERE CODE = 'NC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Painting'
WHERE CODE = 'ND';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Print media'
WHERE CODE = 'NE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Decorative arts'
WHERE CODE = 'NK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Arts in general'
WHERE CODE = 'NX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Language and Literature'
WHERE CODE = 'P';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Philology. Linguistics'
WHERE CODE = 'P';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Greek language and literature. Latin language and literature'
WHERE CODE = 'PA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Modern languages. Celtic languages and literature'
WHERE CODE = 'PB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Romanic languages'
WHERE CODE = 'PC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Germanic languages. Scandinavian languages'
WHERE CODE = 'PD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'English language'
WHERE CODE = 'PE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'West Germanic languages'
WHERE CODE = 'PF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Slavic languages and literatures. Baltic languages. Albanian language'
WHERE CODE = 'PG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Uralic languages. Basque language'
WHERE CODE = 'PH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Oriental languages and literatures'
WHERE CODE = 'PJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Indo-Iranian languages and literatures'
WHERE CODE = 'PK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Languages and literatures of Eastern Asia, Africa, Oceania'
WHERE CODE = 'PL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Hyperborean, Native American, and artificial languages'
WHERE CODE = 'PM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Literature (General)'
WHERE CODE = 'PN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'French literature – Italian literature – Spanish literature – Portuguese literature'
WHERE CODE = 'PQ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'English literature'
WHERE CODE = 'PR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'American literature'
WHERE CODE = 'PS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'German literature – Dutch literature – Flemish literature since 1830 – Afrikaans literature -Scandinavian literature – Old Norse literature: Old Icelandic and Old Norwegian – Modern Icelandic literature – Faroese literature – Danish literature – Norwegian literature – Swedish literature'
WHERE CODE = 'PT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Fiction and juvenile belles lettres'
WHERE CODE = 'PZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Science'
WHERE CODE = 'Q';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Science (General)'
WHERE CODE = 'Q';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Mathematics'
WHERE CODE = 'QA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Astronomy'
WHERE CODE = 'QB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Physics'
WHERE CODE = 'QC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Chemistry'
WHERE CODE = 'QD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Geology'
WHERE CODE = 'QE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Natural history – Biology'
WHERE CODE = 'QH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Botany'
WHERE CODE = 'QK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Zoology'
WHERE CODE = 'QL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Human anatomy'
WHERE CODE = 'QM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Physiology'
WHERE CODE = 'QP';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Microbiology'
WHERE CODE = 'QR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Medicine'
WHERE CODE = 'R';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Medicine (General)'
WHERE CODE = 'R';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Public aspects of medicine'
WHERE CODE = 'RA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Pathology'
WHERE CODE = 'RB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Internal medicine'
WHERE CODE = 'RC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Surgery'
WHERE CODE = 'RD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Ophthalmology'
WHERE CODE = 'RE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Otorhinolaryngology'
WHERE CODE = 'RF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Gynecology and Obstetrics'
WHERE CODE = 'RG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Pediatrics'
WHERE CODE = 'RJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Dentistry'
WHERE CODE = 'RK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Dermatology'
WHERE CODE = 'RL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Therapeutics. Pharmacology'
WHERE CODE = 'RM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Pharmacy and materia medica'
WHERE CODE = 'RS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Nursing'
WHERE CODE = 'RT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Botanic, Thomsonian, and Eclectic medicine'
WHERE CODE = 'RV';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Homeopathy'
WHERE CODE = 'RX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Other systems of medicine'
WHERE CODE = 'RZ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Agriculture'
WHERE CODE = 'S';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Agriculture (General)'
WHERE CODE = 'S';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Horticulture. Plant propagation. Plant breeding'
WHERE CODE = 'SB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Forestry. Arboriculture. Silviculture'
WHERE CODE = 'SD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Animal husbandry. Animal science'
WHERE CODE = 'SF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Aquaculture. Fisheries. Angling'
WHERE CODE = 'SH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Hunting'
WHERE CODE = 'SK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Technology'
WHERE CODE = 'T';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Technology (General)'
WHERE CODE = 'T';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Engineering Civil engineering (General).'
WHERE CODE = 'TA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Hydraulic engineering. Ocean engineering'
WHERE CODE = 'TC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Environmental technology. Sanitary engineering'
WHERE CODE = 'TD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Highway engineering. Roads and pavements'
WHERE CODE = 'TE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Railroad engineering and operation'
WHERE CODE = 'TF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Bridges'
WHERE CODE = 'TG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Building construction'
WHERE CODE = 'TH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Mechanical engineering and machinery'
WHERE CODE = 'TJ';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Electrical engineering. Electronics. Nuclear engineering'
WHERE CODE = 'TK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Motor vehicles. Aeronautics. Astronautics'
WHERE CODE = 'TL';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Mining engineering. Metallurgy'
WHERE CODE = 'TN';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Chemical technology'
WHERE CODE = 'TP';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Photography'
WHERE CODE = 'TR';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Manufacturing engineering. Mass production'
WHERE CODE = 'TS';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Handicrafts. Arts and crafts'
WHERE CODE = 'TT';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Home economics'
WHERE CODE = 'TX';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Military Science'
WHERE CODE = 'U';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Military science (General)'
WHERE CODE = 'U';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Armies: Organization, distribution, military situation'
WHERE CODE = 'UA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Military administration'
WHERE CODE = 'UB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Military maintenance and transportation'
WHERE CODE = 'UC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Infantry'
WHERE CODE = 'UD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Cavalry. Armor'
WHERE CODE = 'UE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Artillery'
WHERE CODE = 'UF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Military engineering. Air forces'
WHERE CODE = 'UG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Other military services'
WHERE CODE = 'UH';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval Science'
WHERE CODE = 'V';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval science (General)'
WHERE CODE = 'V';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Navies: Organization, distribution, naval situation'
WHERE CODE = 'VA';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval administration'
WHERE CODE = 'VB';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval maintenance'
WHERE CODE = 'VC';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval seamen'
WHERE CODE = 'VD';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Marines'
WHERE CODE = 'VE';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval ordnance'
WHERE CODE = 'VF';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Minor services of navies'
WHERE CODE = 'VG';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Navigation. Merchant marine'
WHERE CODE = 'VK';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Naval architecture. Shipbuilding. Marine engineering'
WHERE CODE = 'VM';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Bibliography, Library Science'
WHERE CODE = 'Z';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Books (General). Writing. Paleography. Book industries and trade. Libraries. Bibliography'
WHERE CODE = 'Z';

UPDATE CHINESE_LIBRARY_CLASSIFICATION
SET NAME_EN = 'Information resources/materials'
WHERE CODE = 'ZA';

