DROP TABLE IF EXISTS CHINESE_LIBRARY_CLASSIFICATION;
CREATE TABLE CHINESE_LIBRARY_CLASSIFICATION
(
    CODE        VARCHAR(255) PRIMARY KEY,
    TYPE        VARCHAR(255),
    ENABLE      INT,
    PARENT_CODE VARCHAR(255),
    NAME        TEXT NOT NULL,
    NAME_EN     TEXT NOT NULL,
    DESCRIPTION TEXT
);